code --install-extension 3axap4eHko.file-templates-manager
code --install-extension apollographql.vscode-apollo
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gcazaciuc.vscode-flow-ide
code --install-extension gerane.Theme-Monokai
code --install-extension glen-84.sass-lint
code --install-extension jaredly.reason-vscode
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension leizongmin.node-module-intellisense
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension Orta.vscode-jest
code --install-extension PKief.material-icon-theme
code --install-extension robinbentley.sass-indented
code --install-extension shinnn.stylelint
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
