code --install-extensio 3axap4eHko.file-templates-manager
code --install-extensio apollographql.vscode-apollo
code --install-extensio christian-kohler.path-intellisense
code --install-extensio CoenraadS.bracket-pair-colorizer
code --install-extensio dbaeumer.vscode-eslint
code --install-extensio donjayamanne.githistory
code --install-extensio dsznajder.es7-react-js-snippets
code --install-extensio eamodio.gitlens
code --install-extensio Equinusocio.vsc-material-theme
code --install-extensio esbenp.prettier-vscode
code --install-extensio flowtype.flow-for-vscode
code --install-extensio formulahendry.auto-close-tag
code --install-extensio formulahendry.auto-rename-tag
code --install-extensio gcazaciuc.vscode-flow-ide
code --install-extensio gerane.Theme-Monokai
code --install-extensio glen-84.sass-lint
code --install-extensio jaredly.reason-vscode
code --install-extensio kumar-harsh.graphql-for-vscode
code --install-extensio leizongmin.node-module-intellisense
code --install-extensio mrmlnc.vscode-scss
code --install-extensio ms-azuretools.vscode-docker
code --install-extensio MS-CEINTL.vscode-language-pack-fr
code --install-extensio ms-mssql.mssql
code --install-extensio ms-python.python
code --install-extensio Orta.vscode-jest
code --install-extensio PKief.material-icon-theme
code --install-extensio robinbentley.sass-indented
code --install-extensio shinnn.stylelint
code --install-extensio VisualStudioExptTeam.vscodeintellicode
code --install-extensio vscode-icons-team.vscode-icons
code --install-extensio waderyan.gitblame
code --install-extensio wayou.vscode-todo-highlight
