code --install-extension christian-kohler.path-intellisense ^
code --install-extension CoenraadS.bracket-pair-colorizer ^
code --install-extension dbaeumer.vscode-eslint ^
code --install-extension donjayamanne.githistory ^
code --install-extension dsznajder.es7-react-js-snippets ^
code --install-extension eamodio.gitlens ^
code --install-extension esbenp.prettier-vscode ^
code --install-extension formulahendry.auto-close-tag ^
code --install-extension formulahendry.auto-rename-tag ^
code --install-extension gerane.Theme-Monokai ^
code --install-extension glen-84.sass-lint ^
code --install-extension kumar-harsh.graphql-for-vscode ^
code --install-extension leizongmin.node-module-intellisense ^
code --install-extension mrmlnc.vscode-scss ^
code --install-extension MS-CEINTL.vscode-language-pack-fr ^
code --install-extension ms-mssql.mssql ^
code --install-extension ms-python.python ^
code --install-extension Orta.vscode-jest ^
code --install-extension PeterJausovec.vscode-docker ^
code --install-extension robinbentley.sass-indented ^
code --install-extension shinnn.stylelint ^
code --install-extension waderyan.gitblame ^
code --install-extension wayou.vscode-todo-highlight
